language: node_js
cache: yarn
node_js:
  - stable
  - "10"

script: yarn test

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: yarn test --coverage --coverageReporters=text-lcov | coveralls
